### ISSUE TITLE
How to install diffUTR

### ISSUE THREAD

**Issue by PieraccioliM** [ETHZ-INS/diffUTR#1]
Thanks for this program! I'm very interested in using diffUTR for alternative polyadenylation analysis. I have been trying to install diffUTR, but it requires R >= 4.1 . Currently this version of R is under development. How can I install and use this tool with the datasets of my interest? Thanks!

**Comment by plger** [comment]
Hi,

this is actually a requirement of new Bioconductor submissions, but not strictly required by the package. I've created a branch where this is changed, you can install with:
```
BiocManager::install("ETHZ-INS/diffUTR", ref="r36")
```

If you want to install the development R / Bioc versions (they'll become official releases at the end of April), look up this page:
https://www.bioconductor.org/developers/how-to/useDevel/

**Comment by PieraccioliM** [comment]
Thansk for your kindly reply and for your effort. This is a very interesting tools.
