### ISSUE TITLE
prepareBins path error

### ISSUE THREAD

**Issue by AMChalkie** [ETHZ-INS/diffUTR#3]
When doing the following:

download.file("https://polyasite.unibas.ch/download/atlas/2.0/GRCm38.96/atlas.clusters.2.0.GRCm38.96.bed.gz",destfile="data/apa.mm38.bed.gz")

bins <- prepareBins(g, "data/apa.mm38.bed.gz")
Preparing annotation
Error in open.connection(con, open) : cannot open the connection
In addition: Warning message:
In open.connection(con, open) :
  cannot open compressed file 'apa.mm38.bed.gz', probable reason 'No such file or directory'
  
Can be fixed with copying the file to the current working directory, so it is a path issue in the function.

Best wishes
Alistair

**Comment by chilampoon** [comment]
same here

**Comment by eduardcasas** [comment]
When installing and loading diffUTR from bioconductor I found that many functions were not loaded so I manually had to copy them into new files and source them. I guess you can just export them from github. But maybe this is the issue you find, with the function itself and not the data connection.

**Comment by chilampoon** [comment]
> When installing and loading diffUTR from bioconductor I found that many functions were not loaded so I manually had to copy them into new files and source them. I guess you can just export them from github. But maybe this is the issue you find, with the function itself and not the data connection.

I didn't have the function loading problems though... the issue here is that the function hardcodes the gz file name `apa.mm38.bed.gz`, so with whatever file path we specified, it always finds `apa.mm38.bed.gz` in the working directory but not the user defined one. If saving the bed file (to GRanges object) to an rds file then load it, it works well

**Comment by plger** [comment]
apologies I've no idea why this thread passed completely under my radar... I'll be looking at it asap

**Comment by plger** [comment]
(fix pushed to github, will be in Bioc devel in a couple of days)
